server:
  port: 8080
spring:
  datasource: 
    url: jdbc:mysql://aws.connect.psdb.cloud/prescription?sslMode=VERIFY_IDENTITY
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  main:
    web-application-type: servlet
