server:
  port: 8080
spring:
  datasource: 
    url: jdbc:mysql://aws.connect.psdb.cloud/prescription?sslMode=VERIFY_IDENTITY
    username: jbsjw5k9em2nl9tr79j3
    password: pscale_pw_4n0L4PfYOKYizltAO6rXI7dt997UHettGBIUgNpMDhN
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  main:
    web-application-type: servlet