server:
  port: 8080
spring:
  datasource: 
    url: jdbc:mysql://aws.connect.psdb.cloud/prescription?sslMode=VERIFY_IDENTITY
    username: 6u8jdc8bcl2ul25mbf35
    password: pscale_pw_iigJh8qzoTQiZ2SuKvRwkxmpo0Zow5sLJ0XfZjDC13i
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  main:
    web-application-type: servlet